### PR TITLE
Add MANUAL_INSTRUCTIONS.md (for the paranoid)

### PR DESCRIPTION
**Pull request by rvagg**
I found your scripts and processes a little too obscured, from the confusing scripts to the downloading strange binaries from AWS buckets. Even your Docker container wants access to my ~/.ssh directory, which I'm not very happy with given all of the extra layers.

So, I picked apart your process and documented it such that someone like me not wanting to run your scripts on my computer, can step through easily understandable and slightly more trustworthy steps, with an optional network disconnect when running the installed dependencies.

### CODE REVIEW

**Comment by akim-bow** [comment]
@rvagg Hello, thanks for you submission. Please sign CLA document.

**Review by TriplEight — COMMENTED** [review]
Appreciate the paranoid instructions!
However https://developers.yubico.com/SSH/
> Private keys cannot be exported or extracted from the YubiKey.

And also
> `ssh-rsa` on hardware tokens only supports authentication, not signing

https://github.com/str4d/age-plugin-yubikey/issues/62#issuecomment-1114282464

**Review by akim-bow — CHANGES_REQUESTED** [review]
In case the one uses docker, they want to copy private key inside the docker where everything is set up to make a signature, right? Right know this instruction offers the opposite - copying some private key from docker to the machine.

**Comment by akim-bow** [comment]
Anyway, i can merge it and improve by myself.

**Pull request merged**
